builds:
  - binary: vinocli
    main: .
    ldflags:
      - -s -w
    goos:
      - linux
      - windows
      - darwin
      - macos
    goarch:
      - amd64
      - 386
      - arm
      - arm64

archives:
  - id: binary
    format: binary
